create table Actuaciones_Actuacion (
	uuid_ VARCHAR(75) null,
	actuacionId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	codTecnico LONG,
	nombre VARCHAR(75) null,
	objetivo VARCHAR(75) null,
	descripcion VARCHAR(75) null,
	zona VARCHAR(75) null,
	comunidadAutonoma VARCHAR(75) null,
	provincia VARCHAR(75) null,
	superficie DECIMAL(30, 16) null,
	costeEjecucion DECIMAL(30, 16) null,
	regantes LONG,
	cultivos VARCHAR(75) null,
	situacion VARCHAR(75) null,
	longitud DECIMAL(30, 16) null,
	latitud DECIMAL(30, 16) null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null
);