/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.grupoica.actuaciones.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.math.BigDecimal;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Actuacion service. Represents a row in the &quot;Actuaciones_Actuacion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.grupoica.actuaciones.model.impl.ActuacionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.grupoica.actuaciones.model.impl.ActuacionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Actuacion
 * @generated
 */
@ProviderType
public interface ActuacionModel
	extends BaseModel<Actuacion>, GroupedModel, ShardedModel,
			StagedAuditedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a actuacion model instance should use the {@link Actuacion} interface instead.
	 */

	/**
	 * Returns the primary key of this actuacion.
	 *
	 * @return the primary key of this actuacion
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this actuacion.
	 *
	 * @param primaryKey the primary key of this actuacion
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this actuacion.
	 *
	 * @return the uuid of this actuacion
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this actuacion.
	 *
	 * @param uuid the uuid of this actuacion
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the actuacion ID of this actuacion.
	 *
	 * @return the actuacion ID of this actuacion
	 */
	public long getActuacionId();

	/**
	 * Sets the actuacion ID of this actuacion.
	 *
	 * @param actuacionId the actuacion ID of this actuacion
	 */
	public void setActuacionId(long actuacionId);

	/**
	 * Returns the group ID of this actuacion.
	 *
	 * @return the group ID of this actuacion
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this actuacion.
	 *
	 * @param groupId the group ID of this actuacion
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this actuacion.
	 *
	 * @return the company ID of this actuacion
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this actuacion.
	 *
	 * @param companyId the company ID of this actuacion
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this actuacion.
	 *
	 * @return the user ID of this actuacion
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this actuacion.
	 *
	 * @param userId the user ID of this actuacion
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this actuacion.
	 *
	 * @return the user uuid of this actuacion
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this actuacion.
	 *
	 * @param userUuid the user uuid of this actuacion
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this actuacion.
	 *
	 * @return the user name of this actuacion
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this actuacion.
	 *
	 * @param userName the user name of this actuacion
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this actuacion.
	 *
	 * @return the create date of this actuacion
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this actuacion.
	 *
	 * @param createDate the create date of this actuacion
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this actuacion.
	 *
	 * @return the modified date of this actuacion
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this actuacion.
	 *
	 * @param modifiedDate the modified date of this actuacion
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the cod tecnico of this actuacion.
	 *
	 * @return the cod tecnico of this actuacion
	 */
	public long getCodTecnico();

	/**
	 * Sets the cod tecnico of this actuacion.
	 *
	 * @param codTecnico the cod tecnico of this actuacion
	 */
	public void setCodTecnico(long codTecnico);

	/**
	 * Returns the nombre of this actuacion.
	 *
	 * @return the nombre of this actuacion
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this actuacion.
	 *
	 * @param nombre the nombre of this actuacion
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the objetivo of this actuacion.
	 *
	 * @return the objetivo of this actuacion
	 */
	@AutoEscape
	public String getObjetivo();

	/**
	 * Sets the objetivo of this actuacion.
	 *
	 * @param objetivo the objetivo of this actuacion
	 */
	public void setObjetivo(String objetivo);

	/**
	 * Returns the descripcion of this actuacion.
	 *
	 * @return the descripcion of this actuacion
	 */
	@AutoEscape
	public String getDescripcion();

	/**
	 * Sets the descripcion of this actuacion.
	 *
	 * @param descripcion the descripcion of this actuacion
	 */
	public void setDescripcion(String descripcion);

	/**
	 * Returns the zona of this actuacion.
	 *
	 * @return the zona of this actuacion
	 */
	@AutoEscape
	public String getZona();

	/**
	 * Sets the zona of this actuacion.
	 *
	 * @param zona the zona of this actuacion
	 */
	public void setZona(String zona);

	/**
	 * Returns the comunidad autonoma of this actuacion.
	 *
	 * @return the comunidad autonoma of this actuacion
	 */
	@AutoEscape
	public String getComunidadAutonoma();

	/**
	 * Sets the comunidad autonoma of this actuacion.
	 *
	 * @param comunidadAutonoma the comunidad autonoma of this actuacion
	 */
	public void setComunidadAutonoma(String comunidadAutonoma);

	/**
	 * Returns the provincia of this actuacion.
	 *
	 * @return the provincia of this actuacion
	 */
	@AutoEscape
	public String getProvincia();

	/**
	 * Sets the provincia of this actuacion.
	 *
	 * @param provincia the provincia of this actuacion
	 */
	public void setProvincia(String provincia);

	/**
	 * Returns the superficie of this actuacion.
	 *
	 * @return the superficie of this actuacion
	 */
	public BigDecimal getSuperficie();

	/**
	 * Sets the superficie of this actuacion.
	 *
	 * @param superficie the superficie of this actuacion
	 */
	public void setSuperficie(BigDecimal superficie);

	/**
	 * Returns the coste ejecucion of this actuacion.
	 *
	 * @return the coste ejecucion of this actuacion
	 */
	public BigDecimal getCosteEjecucion();

	/**
	 * Sets the coste ejecucion of this actuacion.
	 *
	 * @param costeEjecucion the coste ejecucion of this actuacion
	 */
	public void setCosteEjecucion(BigDecimal costeEjecucion);

	/**
	 * Returns the regantes of this actuacion.
	 *
	 * @return the regantes of this actuacion
	 */
	public long getRegantes();

	/**
	 * Sets the regantes of this actuacion.
	 *
	 * @param regantes the regantes of this actuacion
	 */
	public void setRegantes(long regantes);

	/**
	 * Returns the cultivos of this actuacion.
	 *
	 * @return the cultivos of this actuacion
	 */
	@AutoEscape
	public String getCultivos();

	/**
	 * Sets the cultivos of this actuacion.
	 *
	 * @param cultivos the cultivos of this actuacion
	 */
	public void setCultivos(String cultivos);

	/**
	 * Returns the situacion of this actuacion.
	 *
	 * @return the situacion of this actuacion
	 */
	@AutoEscape
	public String getSituacion();

	/**
	 * Sets the situacion of this actuacion.
	 *
	 * @param situacion the situacion of this actuacion
	 */
	public void setSituacion(String situacion);

	/**
	 * Returns the longitud of this actuacion.
	 *
	 * @return the longitud of this actuacion
	 */
	public BigDecimal getLongitud();

	/**
	 * Sets the longitud of this actuacion.
	 *
	 * @param longitud the longitud of this actuacion
	 */
	public void setLongitud(BigDecimal longitud);

	/**
	 * Returns the latitud of this actuacion.
	 *
	 * @return the latitud of this actuacion
	 */
	public BigDecimal getLatitud();

	/**
	 * Sets the latitud of this actuacion.
	 *
	 * @param latitud the latitud of this actuacion
	 */
	public void setLatitud(BigDecimal latitud);

	/**
	 * Returns the status of this actuacion.
	 *
	 * @return the status of this actuacion
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this actuacion.
	 *
	 * @param status the status of this actuacion
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this actuacion.
	 *
	 * @return the status by user ID of this actuacion
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this actuacion.
	 *
	 * @param statusByUserId the status by user ID of this actuacion
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this actuacion.
	 *
	 * @return the status by user uuid of this actuacion
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this actuacion.
	 *
	 * @param statusByUserUuid the status by user uuid of this actuacion
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this actuacion.
	 *
	 * @return the status by user name of this actuacion
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this actuacion.
	 *
	 * @param statusByUserName the status by user name of this actuacion
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this actuacion.
	 *
	 * @return the status date of this actuacion
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this actuacion.
	 *
	 * @param statusDate the status date of this actuacion
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this actuacion is approved.
	 *
	 * @return <code>true</code> if this actuacion is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this actuacion is denied.
	 *
	 * @return <code>true</code> if this actuacion is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this actuacion is a draft.
	 *
	 * @return <code>true</code> if this actuacion is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this actuacion is expired.
	 *
	 * @return <code>true</code> if this actuacion is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this actuacion is inactive.
	 *
	 * @return <code>true</code> if this actuacion is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this actuacion is incomplete.
	 *
	 * @return <code>true</code> if this actuacion is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this actuacion is pending.
	 *
	 * @return <code>true</code> if this actuacion is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this actuacion is scheduled.
	 *
	 * @return <code>true</code> if this actuacion is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}